# Generated by Django 5.0.7 on 2024-07-17 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0002_stamps_hikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hikes',
            name='completed_at_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='stamps',
            name='completed_at_date',
            field=models.DateField(),
        ),
    ]
