# Generated by Django 5.0.7 on 2024-07-17 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0003_alter_hikes_completed_at_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamps',
            name='stamp_name',
            field=models.TextField(),
        ),
        migrations.DeleteModel(
            name='Hikes',
        ),
    ]
