# Generated by Django 5.0.7 on 2024-07-17 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0004_alter_stamps_stamp_name_delete_hikes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stamps',
            name='stage_number',
            field=models.IntegerField(),
        ),
    ]
