# Generated by Django 5.0.7 on 2024-07-17 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0007_alter_stamps_stamp_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike_name', models.TextField()),
                ('hike_link', models.URLField()),
                ('starting_point', models.TextField()),
                ('starting_point_elevation', models.IntegerField()),
                ('starting_point_elevation_units', models.TextField()),
                ('lat_start', models.FloatField()),
                ('lon_start', models.FloatField()),
                ('ending_point', models.TextField()),
                ('ending_point_elevation', models.IntegerField()),
                ('ending_point_elevation_units', models.TextField()),
                ('lat_end', models.FloatField()),
                ('lon_end', models.FloatField()),
                ('total_elevation_gain', models.IntegerField()),
                ('total_elevation_gain_units', models.TextField()),
                ('difficulty_level', models.TextField()),
                ('recommended_equipment_summer', models.TextField()),
                ('recommended_equipment_winter', models.TextField()),
                ('page_views', models.IntegerField()),
                ('directions_to_start', models.TextField()),
                ('hike_description', models.TextField()),
                ('completed_at_date', models.DateField()),
                ('stamp_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gorapass.stamps', to_field='stamp_name')),
            ],
        ),
    ]
