# Generated by Django 5.0.7 on 2024-07-17 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0009_alter_hikes_stamp_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Stamp',
        ),
    ]
