# Generated by Django 5.0.7 on 2024-07-18 09:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0012_hikes_stamp_alter_hikes_stamp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikes',
            name='stamp',
        ),
        migrations.AlterField(
            model_name='hikes',
            name='stamp_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gorapass.stamps', to_field='stamp_name'),
        ),
    ]
