# Generated by Django 5.0.7 on 2024-07-18 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0013_remove_hikes_stamp_alter_hikes_stamp_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='hikes',
            name='stamp',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='gorapass.stamps'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hikes',
            name='stamp_name',
            field=models.TextField(),
        ),
    ]
