# Generated by Django 5.0.6 on 2024-07-23 03:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0014_hikes_stamp_alter_hikes_stamp_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hikes',
            name='stamp_name',
        ),
    ]
