# Generated by Django 5.0.6 on 2024-08-02 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gorapass', '0017_alter_completedstamps_user_id_delete_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompletedHikes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveConstraint(
            model_name='completedstamps',
            name='unique_stamp_to_user',
        ),
        migrations.RenameField(
            model_name='completedstamps',
            old_name='stamp_id',
            new_name='stamp',
        ),
        migrations.RenameField(
            model_name='completedstamps',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AddConstraint(
            model_name='completedstamps',
            constraint=models.UniqueConstraint(fields=('stamp', 'user'), name='unique_stamp_to_user'),
        ),
        migrations.AddField(
            model_name='completedhikes',
            name='hike',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gorapass.hikes'),
        ),
        migrations.AddField(
            model_name='completedhikes',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='completedhikes',
            constraint=models.UniqueConstraint(fields=('hike', 'user'), name='unique_hike_to_user'),
        ),
    ]
